config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :haikus
  resources :themes
  resources :users do 
    resources :haikus, only: [:new, :show, :edit, :index, :update, :destroy]
  end 
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get "/auth/github/callback", to: "sessions#create_through_github"
  match '/auth/:provider/callback', to: 'auth#callback', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/haiku.rb
class Haiku < ApplicationRecord
    belongs_to :user
    has_many :haiku_themes
    has_many :themes, through: :haiku_themes

    validates :title, presence: true 
    validates :title, uniqueness: true
    validate :true_haiku
    
    accepts_nested_attributes_for :themes, reject_if: :all_blank
    scope :ordered_by_title, -> { order(title: :asc) }

    def themes_attributes=(theme_attributes)
      theme_attributes.values.each do |theme_attribute|
        if !theme_attribute.empty?
          theme = Theme.find_or_create_by(theme_attribute)
          if !theme.name.empty?
            self.themes << theme
          end 
        end
      end
    end

    def true_haiku
      if line_1.count_syllables != 5
          errors.add(:line_1, "must be 5 syllables long; you have #{line_1.count_syllables}/5")
      elsif line_2.count_syllables != 7
          errors.add(:line_2, "must be 7 syllables long; you have #{line_2.count_syllables}/7")
      elsif line_3.count_syllables != 5
        errors.add(:line_3, "must be 5 syllables long; you have #{line_3.count_syllables}/5")
      end 
    end 

    def content
      content = []
      content << self.line_1
      content << self.line_2
      content << self.line_3
      return content
    end 

    def self.user_with_most_haikus
      self.group(:user_id).count.max_by{|user,count| count }
    end 

end

app/models/haiku_theme.rb
class HaikuTheme < ApplicationRecord
    belongs_to :haiku 
    belongs_to :theme
end

app/models/theme.rb
class Theme < ApplicationRecord
    validates :name, uniqueness: true

    has_many :haiku_themes
    has_many :haikus, through: :haiku_themes

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, presence: true
    validates :username, uniqueness: true
    validates :username, length: { minimum: 4 }
    validates :password, length: { minimum: 6 }
    validates :password_confirmation, presence: true
    has_many :haikus
    has_many :themes, through: :haikus
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def home 
    end 


    private 

    def current_user
       @user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in? 
        session[:user_id]
    end 
end

app/controllers/haiku_themes_controller.rb
class HaikuThemesController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController
  before_action :set_haiku, only: [:show, :edit, :update, :destroy]

  def new
    if params[:user_id]
        user = User.find(params[:user_id])
        @haiku = user.haikus.build
    elsif !params[:user_id]
      @haiku = current_user.haikus.build
    else  
      redirect_to '/'
    end 
  end

  def create
    @haiku = current_user.haikus.build(haiku_params)
    if @haiku.valid?
      @haiku.save 
      redirect_to "/users/#{current_user.id}/haikus/#{@haiku.id}"
    else 
      render "new"
    end 

  end

  def edit
    if @haiku.user == current_user
      render "edit"
    else  
      redirect_to '/'
    end
  end

  def show
    if @haiku.user == current_user
      render "show"
    else 
      redirect_to '/'
    end
  end

  def update
    if @haiku.update(haiku_params) && (@haiku.user == current_user)
      redirect_to "/users/#{current_user.id}/haikus/#{@haiku.id}"
    else 
      render "edit"
    end 
  end

  def index
    if params[:user_id]
      @haikus = User.find(params[:user_id]).haikus
    else 
      @haikus = Haiku.all
    end 
  end

  def destroy
    @haiku.destroy
    redirect_to "/users/#{current_user.id}"
  end 

  private 

  def set_haiku
    @haiku = Haiku.find(params[:id])
  end 

  def haiku_params
    params.require(:haiku).permit(:title, :line_1, :line_2, :line_3, :user_id, theme_ids:[], themes_attributes:[:name])
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
    end 

    def create
        @user = User.find_by(username: params[:user][:username])
        if @user == nil
            flash[:notice] = "Incorrect Username/Password"
            redirect_to login_path
        elsif @user.provider
            flash[:notice] = "Omniauth User Found. Please Use Github"
            redirect_to login_path
        else 
            @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to '/'
        end 
    end 

    def destroy
        session.delete :user_id
        redirect_to '/login'
    end 

    def create_through_github
        if auth = request.env["omniauth.auth"]
            user = User.find_or_create_by(username: auth["info"][:nickname]) do |user|
                user.username = auth["info"][:nickname]
                user.provider = auth.provider
                user.uid = auth.uid
                user.password = auth.uid + auth.provider
                user.password_confirmation = auth.uid + auth.provider
            end
            session[:user_id] = user.id
            redirect_to users_path(user)
        end
    end 

    private

    def auth
        request.env['omniauth.auth']["info"]
    end 
end 

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update]

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.create(theme_params)
    redirect_to theme_path(@theme)
  end

  def edit
  end

  def update
    @theme.update(theme_params)
    redirect_to theme_path(@theme)
  end

  def index
    @themes = Theme.all
  end

  def show
  end

  private 

  def set_theme
    @theme = Theme.find(params[:id])
  end 

  def theme_params
    params.require(:theme).permit(:name)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save 
      session[:user_id] = @user.id
      redirect_to @user
    else 
      render 'new'
    end 
  end

  def show
    redirect_to '/' unless logged_in?
  end

  def index
  end 

  private
  
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end 

  def set_user
    @user = User.find_by(id: params[:id])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/haiku_themes_helper.rb
module HaikuThemesHelper
end

app/helpers/haikus_helper.rb
module HaikusHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<h1>Hi there!</h1>
<h3> Ready to be part of HaikuMe? </h3>

app/views/haikus/_form.html.erb
<%= form_for haiku do |f| %>
  <% if haiku.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(haiku.errors.count, "error") %>
      prohibited this Haiku from being saved:
    </h2>

    <ul>
    <% haiku.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

    <div class="field">
    <%= f.label :title, "Title: " %>
    <br>
    <%= f.text_field :title %>
    <p>
    Content:
    <br>
    <%= f.label :line_1, "Line 1:" %>
    <%= f.text_field :line_1 %>
    <br>
    <%= f.label :line_2, "Line 2:" %>
    <%= f.text_field :line_2 %>
    <br>
    <%= f.label :line_3, "Line 3:" %>
    <%= f.text_field :line_3 %>
    </p>
    </div>


    <div class="field">
    <%= f.label :theme %>
    <br>
    <%= f.collection_check_boxes :theme_ids, Theme.all, :id, :name %>
    </div>

    <br>
    <div class="field">
    Create a new Theme
    <br>
    <%= f.fields_for :themes, haiku.themes.build do |themes_fields| %>
        <%= themes_fields.text_field :name %>
    <% end %>
    </div>

    <br>
    <%= f.submit %>
<% end %>

<%if !(haiku.id == nil) %>
Or 
<%= button_to "Delete Haiku", haiku_path(haiku), method: :delete %>
<%end%>

app/views/haikus/edit.html.erb
<%= render partial: 'form', locals: {haiku: @haiku} %>

app/views/haikus/index.html.erb
<% if !@haikus.empty? %> 
    <% @haikus.ordered_by_title.each do |haiku| %>
        <p>
        <b><%= haiku.title.capitalize%></b>
        <br>
        By: <%= link_to haiku.user.username.capitalize, user_haikus_path(haiku.user)%>
        <%haiku.content.each do |line|%>
            <p> 
            <%=line%>
            </p>
        <%end%>
        </p>
        <% if haiku.user == current_user %>
        <%= link_to "Edit", "/users/#{current_user.id}/haikus/#{haiku.id}/edit"%>
        <%end%>
    <% end %>
<%else%> 
No Haikus, yet...
<%end%>

app/views/haikus/new.html.erb
<%= render partial: 'form', locals: {haiku: @haiku} %>

app/views/haikus/show.html.erb
<b><%= @haiku.title %></b>
<br>
By: <%= link_to @haiku.user.username.capitalize, user_haikus_path(@haiku.user)%>
<p>
  Haiku: 
  <br>
  <%@haiku.content.each do |line|%>
    <p> 
    <b><%=line%></b>
    </p>
<%end%>
  </p>

Themes:
<br>
  <%= @haiku.themes.each do |f|%>
    <%if !f.name.empty?%>
    <%= f.name%>
    <br>    
    <%end %>
    <%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<center>
  <head>
    <title>HaikuMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= yield %>
  </body>
  <br>
  <br>
  <hr>
  <% if !current_user %>
  <li><%= link_to "Sign Up!", "/signup"%></li>
  <br>
  <br>
  <li> <%= link_to "Log In!", "/login"%></li> 
  <%else%>
  <li><%= link_to "New Haiku!", "/users/#{current_user.id}/haikus/new"%></li>
    <br>
    <li><%= link_to "Profile", "/users/#{current_user.id}"%></li>
    <br>
    <li><%= link_to "Log Out", "/logout", method: :post %></li>
    <%end%>
    <br>
    <li><%= link_to "Home", "/"%></li>
    <br>
    <li> <%= link_to "Haiku Catalog", "/haikus" %>
    </center>
</html>

app/views/themes/_form.html.erb
<%= form_for theme do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/themes/edit.html.erb
<%= render partial: 'form', locals: {theme: @theme} %>

app/views/themes/index.html.erb
<% @themes.each do |theme| %>
    <li>
    <%= link_to theme.name, theme_path(theme) %>
    </li>
<% end %>

app/views/themes/new.html.erb
<%= render partial: 'form', locals: {theme: @theme} %>

app/views/themes/show.html.erb
<% @theme.haikus.each do |haiku| %>
    <%= link_to haiku.title, haiku %>
  <% end %>

app/views/users/_form.html.erb
<h1> Sign Up </h1>

<%= form_for user do |f| %>
  <% if user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>

    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

    <%= f.label :username, "Username: " %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :password, "Password: " %>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.label :password_confirmation, "Confirm Password: " %>
    <%= f.password_field :password_confirmation %>
    <br>
    <br>
    <%= f.submit "Sign up" %>
<% end %>

app/views/users/edit.html.erb
<%= render partial: 'form', locals: {user: @user} %>

app/views/users/index.html.erb
Hello <%= "#{current_user.username}"%>

app/views/users/new.html.erb
<%= render partial: 'form', locals: {user: @user} %>

<br>
<%= button_to 'Sign up with Github', '/auth/github'%>

app/views/users/show.html.erb
<br>
<h1> Hi <%= @user.username.capitalize %>!</h1>
<br>
<%if @user.haikus.empty? %>
    <%= "#{@user.username} has no Haikus yet" %>
<%else%> 
    Your Haikus:
    <br>
    <%@user.haikus.each do |haiku|%>
        <p>
        <b><%= haiku.title %></b>
        <br>
            <%haiku.content.each do |line|%>
                <p> 
                <%=line%>
                </p>
            <%end%>
            <%= link_to "View", "/users/#{current_user.id}/haikus/#{haiku.id}"%>
            <br>
            <%= link_to "Edit", "/users/#{current_user.id}/haikus/#{haiku.id}/edit"%>
            <br>
            <br>
            <%= button_to "Delete Haiku", haiku_path(haiku), method: :delete %>
            </p>
            <br>
        <%end%>
    <%end%>
    <br>

    <%if @user.themes.empty? %>
    <%= "#{@user.username} has no themes yet" %>
<%else%> 
    Your Themes:
    <br>
    <%@user.themes.uniq.each do |t|%>
        <p>
        <b><%= t.name %></b>
        <br>
        <%end%>
        <%end%>